version: '3.8'
services:

  db:
    image: postgres
    restart: always
    container_name: users_db
    environment:
      POSTGRES_USER: nikita
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: users_service_image
    container_name: users_service
    ports:
      - 5000:80
    depends_on:
      - db
    networks:
      - db-network

  redis:
    image: redis:latest
    restart: always
    command: redis-server
    volumes:
      - redis-data:/data
      - redis-config:/usr/local/etc/redis/redis.conf
      - redis:/var/lib/redis
    ports:
      - 6379:6379
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis:
  redis-data:
  redis-config:
  postgres_data:
networks:
  redis-network:
    driver: bridge
  db-network:
    driver: bridge
